// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOy14ef8jaRy4NKdwWVr8U1sB4ErDyVRY',
    appId: '1:408624907995:web:7d68b5b15737947e82aefe',
    messagingSenderId: '408624907995',
    projectId: 'smart-india-hackathon-20-b7412',
    authDomain: 'smart-india-hackathon-20-b7412.firebaseapp.com',
    storageBucket: 'smart-india-hackathon-20-b7412.appspot.com',
    measurementId: 'G-8G9QTR2E7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD7fBYS2lWODnEr6m5WuGPsiE6J15X0zs',
    appId: '1:408624907995:android:c37c03153a263dc182aefe',
    messagingSenderId: '408624907995',
    projectId: 'smart-india-hackathon-20-b7412',
    storageBucket: 'smart-india-hackathon-20-b7412.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHLonhpE8_rELR7y0Vonrma3KryADtuGc',
    appId: '1:408624907995:ios:b6d82d310bb44dde82aefe',
    messagingSenderId: '408624907995',
    projectId: 'smart-india-hackathon-20-b7412',
    storageBucket: 'smart-india-hackathon-20-b7412.appspot.com',
    iosBundleId: 'com.innovision.smartIndiaHackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHLonhpE8_rELR7y0Vonrma3KryADtuGc',
    appId: '1:408624907995:ios:e8f82cdb607c7f5f82aefe',
    messagingSenderId: '408624907995',
    projectId: 'smart-india-hackathon-20-b7412',
    storageBucket: 'smart-india-hackathon-20-b7412.appspot.com',
    iosBundleId: 'com.innovision.smartIndiaHackathon.RunnerTests',
  );
}
